HC-2302 Support auth by default SSH keys and user/pwd (for HTTP)
jamf/rendr pull request #16
Opened 2020-10-02 13:18 UTC by uint-jamf

For now, this handles
* SSH by trying to find the default SSH private key in `~/.ssh/` (it tries to read the username from the URL, but will prompt if missing)
* HTTP(S) by prompting for user/pass

@thecodesmith I'm thinking we probably also want the option to provide user/pass through CLI args, and especially the password through env vars. Do we stop there, or also add an argument for specifying the SSH key?

2020-10-05 18:19 UTC, uint-jamf commented
Think this is good for review!

2020-10-05 18:44 UTC, thecodesmith requested changes
I get this when trying to use an HTTPS blueprint that requires auth:
```
❯ cargo run -- init foo -b https://stash.jamf.build/scm/~brian.stewart/example-blueprint.git

    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/rendr init foo -b 'https://stash.jamf.build/scm/~brian.stewart/example-blueprint.git'`
[DEBUG rendr::init] Git requested cred types: USER_PASS_PLAINTEXT
Username: brian.stewart
Password:
[DEBUG rendr::blueprint] No post-render script found in blueprint scripts directory - skipping
example-blueprint v1
Brian S. <brian.stewart@jamf.com>, Tomasz K. <tomasz.kurcz@jamf.com>
Just an example blueprint for `express`.

[INFO  rendr::init] Output directory: "foo". Creating your new scaffold...
[DEBUG rendr::blueprint] Creating root project dir "foo"
[ERROR rendr] Error { depth: 0, inner: Io { path: Some("/var/folders/q9/79nmvhy97g5f5j2t65r1d2p80000gn/T/checked_out_blueprint.aeC2RYRoiGZX/template"), err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }
```
There is actually no error message at the INFO level, only debug. After the command exits, there is a new `foo/` dir, but it is empty.

2020-10-05 18:44 UTC, thecodesmith commented on src/bin/init.rs
> +        .is_none());
This is actually more confusing on a separate line I think, since it is not at the same level as the `.filter` call above it, it's actually inside it.

2020-10-05 18:44 UTC, thecodesmith commented on src/blueprint/source.rs
> +        // Repository::clone(url, &dir)?;
Does this need to be uncommented or removed?

2020-10-06 05:58 UTC, uint-jamf commented on src/bin/init.rs
> +        .is_none());
This is what I get for late night coding. Yeah, I thought I was "fixing" it.

2020-10-06 10:40 UTC, uint-jamf commented
> cargo run -- init foo -b https://stash.jamf.build/scm/~brian.stewart/example-blueprint.git

Oddly, this works for me for [my own private repo on Stash](https://stash.jamf.build/users/tomasz.kurcz/repos/test/browse).

```
❯ cargo run -- init -b https://bitbucket-mirroreucentral1.eu.jamf.build/scm/stash/~tomasz.kurcz/test.git ASD
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/rendr init -b 'https://bitbucket-mirroreucentral1.eu.jamf.build/scm/stash/~tomasz.kurcz/test.git' ASD`
[DEBUG rendr::init] Git requested cred types: USER_PASS_PLAINTEXT
Username: tomasz.kurcz
Password: 
[DEBUG rendr::blueprint] No post-render script found in blueprint scripts directory - skipping
The name of your project: 
example-blueprint v1
Brian S. <brian.stewart@jamf.com>, Tomasz K. <tomasz.kurcz@jamf.com>
Just an example blueprint for `rendr`.

[INFO  rendr::init] Output directory: "ASD". Creating your new scaffold...
[DEBUG rendr::blueprint] Creating root project dir "ASD"
[DEBUG rendr::blueprint] Found file "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/another-test.yaml"
[DEBUG rendr::blueprint] Using template "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/another-test.yaml" to render "ASD/another-test.yaml"
[DEBUG rendr::blueprint] Found file "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/test.yaml"
[DEBUG rendr::blueprint] Using template "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/test.yaml" to render "ASD/test.yaml"
[DEBUG rendr::blueprint] Found file "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/excluded_file"
[DEBUG rendr::blueprint] Copying "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/excluded_file" to "ASD/excluded_file" without templating.
[DEBUG rendr::blueprint] Creating directory "ASD/dir"
[DEBUG rendr::blueprint] Found file "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/dir/test.yaml"
[DEBUG rendr::blueprint] Using template "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/dir/test.yaml" to render "ASD/dir/test.yaml"
[DEBUG rendr::blueprint] Creating directory "ASD/excluded_files"
[DEBUG rendr::blueprint] Found file "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/excluded_files/foo"
[DEBUG rendr::blueprint] Copying "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/excluded_files/foo" to "ASD/excluded_files/foo" without templating.
[DEBUG rendr::blueprint] Found file "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/excluded_files/bar"
[DEBUG rendr::blueprint] Copying "/var/folders/fn/3xthcvp944b27ckbm30d3_gm0000gn/T/checked_out_blueprint.b3ICqU5kNI9X/template/excluded_files/bar" to "ASD/excluded_files/bar" without templating.
[DEBUG rendr::blueprint] Generating .rendr.yaml file:
[DEBUG rendr::blueprint]   source: https://bitbucket-mirroreucentral1.eu.jamf.build/scm/stash/~tomasz.kurcz/test.git
[DEBUG rendr::blueprint]   output_dir: ASD
[DEBUG rendr::blueprint]   values: {"name": "asd", "version": "1"}
[DEBUG rendr::init] Initializing Git repository
[INFO  rendr::init] Success. Enjoy!
```

2020-10-06 10:45 UTC, uint-jamf commented
To the bug you've found: I think you're actually using the old model in that repo, with the templates sitting in a `blueprint` folder rather than a `template` one. `rendr` tries to find `template` and fails.

2020-10-06 10:59 UTC, uint-jamf commented on src/blueprint/source.rs
> +        // Repository::clone(url, &dir)?;
Removed, you're right!

2020-10-12 14:43 UTC, thecodesmith approved these changes
Looks good! That error was definitely on my end.

2020-10-13 09:39 UTC, merged